apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mukesh9467/ci-demo.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ci-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
