apiVersion: v1
kind: Service
metadata:
  name: ci-demo-app
  namespace: ci-demo
  labels:
    app: ci-demo-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: ci-demo-app
